version: '3.2'
services:
  backend:
    image: scopeinfinity/video2description:deploy
    environment:
      V2D_CONFIG_FILE: config_docker.json
    networks:
      internal:
        ipv4_address: 172.14.0.2
    volumes:
       - uploads:/home/si/v2d/uploads/:ro
       - ./src:/home/si/v2d/src/:ro
    entrypoint: /bin/bash -i -c 'python -m backend.parser server -s -m /home/si/v2d/models/ResNet_D512L512_G128G64_D1024D0.20BN_BDGRU1024_D0.2L1024DVS_model.dat_4983_loss_2.350_Cider0.355_Blue0.353_Rouge0.571_Meteor0.247_TOTAL_1.558_BEST 2>&1'

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: scopeinfinity/video2description:frontend
    ports:
      - "8080:5000"
    environment:
      V2D_CONFIG_FILE: config_docker.json
    networks:
      internal:
        ipv4_address: 172.14.0.3
    volumes:
       - uploads:/home/si/v2d/uploads/
       - ./src:/home/si/v2d/src/:ro
    entrypoint: /bin/bash -c 'python -m frontend.app 2>&1'

volumes:
  uploads:

networks:
  internal:
     ipam:
      driver: default
      config:
        - subnet: "172.14.0.0/24"